// CommonJS, every file is module (by default);
// Modules - Encapsulated Code (only share minimum);
const names = require("./4-names");
const banana = require("./5-utils");
const data = require("./6-alternative-flavor");
require("./7-mind-grenade");
banana("lior");
banana(names.amit);
banana(names.ronit);
console.log(data);
